### ISSUE TITLE
Should we define UDF types?

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-udf#4]
Currently UDF's have a very generic interface, which allows it to have a wide range of inputs and outputs.
However, in a  process graph, the provided UDF needs to be compatible with the OpenEO process that will invoke it.
Some possible example 'interface definitions':
applyTiles(tile) -> tile
applyFeatures(featurecollection) -> featurecollection
applyTimeseries(List<tile>) -> List<tile>
aggregateTimeseries(List<tile>) -> tile

In the backend, this is relevant in the sense that this impacts possible performance optimizations.
For the UDF implementor, this might also simplify things. For instance, when computing an NDVI (or other pixel based vegetation index), he should not have to deal with the time dimension. (Like is currently the case in the NDVI example UDF.)

**Comment by m-mohr** [comment]
See also https://github.com/Open-EO/openeo-api/issues/19

**Comment by pramitghosh** [comment]
Yes, I think having having a formal definition for the UDF types would be helpful. For the R implementation for the UDFs, for example, each of the UDF types (say "reduce time", "reduce space" etc.) are associated with a set of values (one for each dimension) which defines which dimension is being added/dropped. @flahn has implemented this concept as a "dimensionality modifier" which is associated with each UDF type. The objects holding the data ("Collection" objects) too have a "dimensionality" associated with it and running a UDF (or any other process for that matter) would modify this "dimensionality" accordingly.

Having such a formalization could act as a layer for some sort of type-checking to see if an UDF is applicable on the intermediate object while executing the Process Graph, which was the motivation for its design and implementation by Florian and me. Having this could also be useful for other purposes like chunking the data before executing UDFs along a suitable dimension (based on which dimension the UDF is working on) for parallel processing of the UDFs.

**Comment by GreatEmerald** [comment]
Well, defining them seems to have been the original plan all along? i.e. https://open-eo.github.io/openeo-api/v/0.0.2/udfs/index.html

**Comment by jdries** [comment]
This is getting more urgent, as we need to define this now also in our process catalogue.
At this moment, I'm working on the raster_collections_reduce_time_sum.py udf. This type of UDF reduces the pixels over the time dimension. In Earth Engine, this operation is simply called 'reduce'. 
So possible names include:

- reduce
- reduce_time
- aggregate_time
- apply_to_pixel_timeseries

One important variable is whether or not the UDF works on a single pixel, or requires a larger neighborhood. We can either make this clear with some kind of parameter, or use separate methods for this.

Any suggestions on which name to choose?

**Comment by m-mohr** [comment]
We should align that with the other processes we define for non-UDF processing in the next weeks. 

We'll probably have general purpose processes such as reduce (lowering dimensionality), aggregate and filter (same dimensionality, but lower resolution) anyway.
* These should be able to work on different dimensions, e.g. spatial, temporal/time, etc.
* These should have a parameter that specifies a reduce/filter/... function. These reduce/... functions should be well defined and be a process again, e.g. min/max/ etc.
* I think it is better to have separate names to separate single pixel/neighborhood operations.
* What I am not sure about is whether we need separate definitions for UDFs or not?
    It could be reduce(dimension = "temporal", function = min) where `min` is a pre-defined `min` process, but `function` could also take a UDF. Or is it separated into e.g. `process` and `udf`?

There is a similar proposal from Edzer, which you can find in the OwnCloud next to the Use Case processes.

**Comment by pramitghosh** [comment]
Just as a quick note, in order to differentiate between the UDF types that @jdries mentioned, the approach that is being currently used for R UDFs considers separate native methods for each of them which the user's script has to be registered against in the backend. But, of course, everything is subject to modification if required.

Yes, actually we could have two varieties of UDFs - one for simple functions such as `min`, `max`, `mean`, `median` etc. which would specify how the data will be reduced along a dimension (e.g. time, band etc.). The other variety could be used for more complicated generic UDFs where the operation might not correspond to any of the pre-defined UDF types - such as changing the Coordinate Reference System of the collection. This would give the users more freedom. I've implemented this experimentally as a PoC for the R UDFs with two endpoints `/udf` and `/udf/raw` for these two varieties.

However, for @m-mohr 's last point, do you mean to have `reduce(dimension = "temporal", function = min)` for UDFs or native processes? I think for UDFs it's better to have the user's script alone which would allow them to have their own custom reduce operations (e.g. "min over time and add 100 to each band"). For native processes using something as you mentioned is fine though.

**Comment by m-mohr** [comment]
That was an example for a process. For UDFs it could be something like `reduce(dimension = "temporal", function = "whatever_udf.py")`. But my question there was whether they should share a parameter name or be separate parameters, e.g. udf = ... and process = ....

**Comment by pramitghosh** [comment]
@m-mohr  Ahh, right. I think another possible option would be to have processes having an attribute somewhere which determines whether it's associated with UDFs or not (i.e. whether it could take users' scripts as the `function` as you mentioned), if this is what you mean. For example, we could have a process corresponding to each of the UDF types, as mentioned previously.

**Comment by jdries** [comment]
Some specific UDF signatures are now supported, like 'apply_timeseries', 'apply_datacube'.
This at least makes UDF's more user friendly to write, with less boilerplate for simple cases.
Other signatures could be added, but UDF's need to be more widely supported first IMO.
